# Setup the server
server:
  port: 3000
  # Configure SSL. Add the path to the key and certificate file
  ssl:
    key:
    cert:

# Configure the Redis like message backend.
redis:
  port: 6379
  host: 127.0.0.1
  password: jgsay7f2fgfgda6acCa7g()jaba51!

# Configure the postgresql database
database:
  user: sitespeedio
  server: 127.0.0.1
  name: sitespeedio
  password: jhde7gFArda33Saa1!4dd2dagJ
  port: 5432

# Configure the log.
log:
  verbose: false

# Make sure only users with the correct key can add tests
api:
  key:

# Regular expression that needs to match the domain that you test. If there's a miss match, no tests will run.
validTestDomains: "^(?:[\\w-]+\\.)*wikipedia\\.org$"

# You can disable the GUI if you only want to add test through the API
disableGUI: false

# You can disable searching through the GUI
disableSearchGUI: false

# How many max entries do you want per page?
search:
  resultPerPage: 100
  # Show slug in search result
  showSlug: false
  # Show the label in the search result
  showLabel: true
## Configure the GUI
html:
  css:
    override:
  logo:
    path: "/img/logo.svg"
    width: 300
    alt: "sitespeed.io logo"
  logoHeader:
    path: "/img/logoHeader.svg"
    width: 112
    height: 18
    alt: "sitespeed.io logo"
  favicon-180:
    path: /img/ico/sitespeed.io-180.png
  favicon-32:
    path: /img/ico/sitespeed.io-32.png
  ## Setup a folder that will be mapped to /extras - use this of you want to change
  ## the current look and feel
  extras:
    path:
  # You can choose to either show the log from sitespeed.io or a random AI generated image.
  showRandomAIImage: false
  # Show the Lighthouse box
  useLighthouse: false

# How to format dates
dateformat: "YYYY-MM-DD HH:mm:ss"

# You can localize the text
localization:
  locale: en
  # You can also configure where the text is stored
  # directory: ./locales

# You can setup basic auth for accesss. If you configure both login and password
# it will be applied. It's on all pages except the /api/ and /admin/
basicAuth:
  login:
  password:

# Admin has its own basic auth
admin:
  basicAuth:
    login: appojke
    password: monkeyboy

# The number of jobs to keep in the queue
# Depending on how many jobs you run and how much memory
# you have on your Redis/KeyDb instance you can tune this
queue:
  removeOnComplete: 50
  removeOnFail: 50


# The default sitspeed.io configuration file that will be merged to all tests.
# defaultSitespeedioConfigFile:

# If you don't setup a default sitespeed.io configuration, you can add
# your sitespeed.io configuration directly in this block
sitespeed.io: